feat: convert FormAssociated to a constructable function
microsoft/fast pull request #4115
Opened 2020-11-12 03:00 UTC by radium-v

# Description
Converts `FormAssociated` to be a "constructable" function call that returns a mixin class.

## Motivation & context
Allows for easier control when working with mixin classes and `FormAssociated`.

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [ ] **Bug fix**: A change that fixes an issue, link to the issue above.
- [x] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**
This modifies all `FormAssociated`-based components:
- Button
- Checkbox
- Radio
- Slider
- Text Area
- Text Field

- [ ] I have added a new component
- [x] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist

- [x] I have added tests for my changes.
- [x] I have tested my changes.
- [x] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

2020-11-12 03:02 UTC, radium-v commented
@nicholasrice there are still two tests that are breaking for me which were added recently, can you take a look and see if there's a quick fix?

2020-11-12 16:12 UTC, EisenbergEffect requested changes
I like this change. I made one request to move an interface. If we can make that change and get the tests all passing, I think we're good.

2020-11-12 16:12 UTC, EisenbergEffect commented on packages/web-components/fast-foundation/src/utilities/constructable.ts
> +export type Constructable<T = {}> = {
I think we could move this to fast-element and make it a public export. We've got multiple uses for this and I think it's something that fits in at the lowest level.

2020-11-12 17:49 UTC, nicholasrice commented
I *think* the `FormAssociated` test assertion can be changed to expect empty string. At this point I don't recall why that test is there, but if you check the `value` property of an `<input>` prior to connection it is empty string, so I think we should match that behavior.

2020-11-13 18:54 UTC, nicholasrice approved these changes
Thanks @radium-v - this is awesome.

2020-11-13 18:59 UTC, chrisdholt approved these changes
That's a lot of updates :)

Thanks @radium-v!

2020-11-13 19:00 UTC, EisenbergEffect approved these changes

2020-11-13 19:38 UTC, merged