add initial migration documentation for v1 to v2
microsoft/fast pull request #4762
Opened 2021-05-22 02:36 UTC by janechu

# Pull Request

## 📖 Description

This adds initial documentation for the site for v1 to v2 of the packages `@microsoft/fast-element`, `@microsoft/fast-foundation` and `@microsoft/fast-components`. This assumes that all three packages will major version bump.

## 👩‍💻 Reviewer Notes

Please check the wording carefully, this documentation is based on my recent experience with migrating the experimental web components in the `@microsoft/fast-tooling` package.

## ✅ Checklist

### General

- [ ] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [x] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## ⏭ Next Steps

2021-05-22 02:51 UTC, chrisdholt approved these changes

2021-05-24 01:14 UTC, EisenbergEffect requested changes
One minor change.
QQ: Do we want to add this to the site ToC? If so, where should we put it?

2021-05-24 01:14 UTC, EisenbergEffect commented on sites/website/src/docs/migrate/1-to-2.md
> +This guide aims to help you migrate from `@microsoft/fast-element`, `@microsoft/fast-foundation`, and `@microsoft/fast-components` v1 to v2.
No changes to `@microsoft/fast-element` so that can be removed from here.

2021-05-24 15:38 UTC, nicholasrice approved these changes
Thanks Jane! I'll do some iterations on this once we get it in.

2021-06-10 15:25 UTC, bheston commented
This is a good start. I see Nick said he would add to it. For instance we're missing a note about migrating color recipes from behaviors.

I think the descriptions in each section are helpful, but I wonder if we should also have a quick checklist like
- Update components to extend FoundationElement
- Replace template definition from a to b
- Replace style definition...
- Search and replace `behavior.var`
- Remove color behavior imports and withBehaviors
- etc

Those might be the bulk of the steps, tersely written obviously.

2021-06-25 00:27 UTC, janechu commented
Closing this as the migration documents are being re-written within an updated docs site structure.

2021-06-25 00:27 UTC, closed without merging