fix: initial value in FAST select control not used when using Angular two-way binding
microsoft/fast pull request #5257
Opened 2021-10-05 22:03 UTC by brianehenry

# Pull Request

## 📖 Description

The FAST select control fails to accept its initial value when it is set right after the select is connected. This change handles that case by marking the `option` element corresponding to the given value with the `selected` attribute. 

### 🎫 Issues

#5139 

## 👩‍💻 Reviewer Notes

## 📑 Test Plan

Added one unit test that reflects the desired behavior.

## ✅ Checklist

### General

- [x] I have included a change request file using `$ yarn change`
- [x] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## ⏭ Next Steps

2021-10-06 19:30 UTC, radium-v requested changes
Hi @brianehenry, thanks for investigating this issue. I downloaded and ran the angular demo from #5139 to make sure my review is accurate.

The approach works for setting the default selected option when `ngModel` is used, but there are two problems:
* It sets the `selected` attribute on the matching `fast-option`, which can cause collisions when both a default `value` exists and an initial child option already has the `selected` attribute.
* It runs the check every time `value` is updated.

Since we only need it to check this when the component is connected, we can override the `setDefaultSelectedOption()` method for `Select` in the same way that `Combobox` does it.

This override function is a modified version from `Listbox`, which allows the options list to fallback to the filtered list of child elements, and adds a `value` check for each option:

```ts
    protected setDefaultSelectedOption(): void {
        if (this.$fastController.isConnected) {
            const options: ListboxOption[] =
                this.options ??
                Array.from(this.children).filter(Listbox.slottedOptionFilter);

            const selectedIndex = options?.findIndex(
                el =>
                    el.getAttribute("selected") !== null ||
                    el.selected ||
                    el.value === this.value
            );

            if (selectedIndex !== -1) {
                this.selectedIndex = selectedIndex;
                return;
            }

            this.selectedIndex = 0;
        }
    }
```

Then to make sure the `formResetCallback` functions as expected, we can change the method to call the super method:

```ts
public formResetCallback = (): void => {
    this.setProxyOptions();
    super.setDefaultSelectedOption();
    this.value = this.firstSelectedOption.value;
};
```

2021-12-22 16:45 UTC, brianehenry commented
Hi @radium-v, thanks for the detailed feedback. 

I tried out your suggested changes, but they don't seem to fix the issue that I'm seeing (or, at least, the test case I wrote fails with those changes). The issue with your suggestion is that it relies on the select's private `_value` field being set by the `value` setter. But the `value` setter does not set `_value` if it does not find a matching `option` element with the same `value` string, which is the case when the `options` property has not yet been initialized. So, when `setDefaultSelectedOption()` is called, the select's `value` property is still unset.

I updated my PR to address the first issue you had with my changes - the select will now clear any previously set `selected` attribute on the option elements. I don't think the second issue you raised is a showstopper, as the `value` setter won't call any of the code I added after the `options` property is initialized.

2022-02-04 16:45 UTC, EisenbergEffect commented
@radium-v Can you take a look at this one again. Brian has made some changes since your last feedback.

2022-02-07 16:27 UTC, brianehenry commented
@radium-v Provided some additional feedback [on discord](https://discord.com/channels/449251231706251264/449251231706251266/931692250679873547). I applied the suggested changes to my branch.

2022-02-07 17:00 UTC, EisenbergEffect approved these changes
Just need a bit of code commenting for the on out-of-the-ordinary situation noted below.

2022-02-07 19:28 UTC, radium-v commented on packages/web-components/fast-foundation/src/select/select.ts
> +                el.getAttribute("selected") !== null ||
My bad, there's a better check for this:

```suggestion
                el.hasAttribute("selected") ||
```

2022-02-07 19:29 UTC, radium-v approved these changes

2022-02-08 20:58 UTC, brianehenry commented on packages/web-components/fast-foundation/src/select/select.ts
> +        super.setDefaultSelectedOption();
Added a comment with an explanation. For what it's worth, I find it strange to call a `super` method from anywhere besides its override, but I don't see an obvious alternative here.

2022-02-09 19:21 UTC, brianehenry commented
@chrisdholt @EisenbergEffect This PR is ready to be merged.

2022-02-09 19:50 UTC, merged