add links back to cheat sheet
microsoft/fast pull request #5486
Opened 2021-12-20 20:13 UTC by huynhicode

# Pull Request

## 📖 Description

Linking back to the Cheat Sheet from the Docs.

### 🎫 Issues

None

## 👩‍💻 Reviewer Notes

Please review the verbiage and corresponding links.

## 📑 Test Plan

None

## ✅ Checklist

### General

- [x] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## ⏭ Next Steps

2021-12-22 14:35 UTC, awentzel approved these changes

2022-01-06 05:33 UTC, chrisdholt approved these changes

2022-01-06 22:12 UTC, janechu approved these changes

2022-01-11 16:45 UTC, EisenbergEffect requested changes

2022-01-11 16:45 UTC, EisenbergEffect commented on packages/web-components/fast-element/README.md
> +Looking for a quick guide on building components?  Check out [our Sheet Cheat](https://www.fast.design/docs/resources/cheat-sheet#building-components).
```suggestion
Looking for a quick guide on building components?  Check out [our Cheat Sheet](https://www.fast.design/docs/resources/cheat-sheet#building-components).
```

2022-01-11 16:45 UTC, EisenbergEffect commented on packages/web-components/fast-element/docs/guide/declaring-templates.md
> +Check out [our Sheet Cheat](https://www.fast.design/docs/resources/cheat-sheet#bindings) for a quick guide on bindings.
```suggestion
Check out [our Cheat Sheet](https://www.fast.design/docs/resources/cheat-sheet#bindings) for a quick guide on bindings.
```

2022-01-11 16:45 UTC, EisenbergEffect commented on packages/web-components/fast-element/docs/guide/next-steps.md
> +For a quick guide, check out [our Cheat Sheet](https://www.fast.design/docs/resources/cheat-sheet).
```suggestion
For a quick reference on what you've learned, check out [our Cheat Sheet](https://www.fast.design/docs/resources/cheat-sheet).
```

2022-01-11 16:45 UTC, EisenbergEffect commented on sites/website/src/docs/introduction.md
> +* "I want to look at a quick guide."
```suggestion
* "I want to look at a quick reference."
```

2022-01-11 20:37 UTC, huynhicode commented
@EisenbergEffect Thank you for those catches and verbiage update suggestions!

2022-01-12 01:01 UTC, EisenbergEffect approved these changes

2022-01-12 02:08 UTC, merged