doc: configure ejected create-react-app to support decorators
microsoft/fast pull request #5682
Opened 2022-03-01 19:19 UTC by prudepixie

# Pull Request

## 📖 Description

Add documentation in the create-react-app section to support decorators in the babel build options.
Closes #5634

### 🎫 Issues
#5634

## 👩‍💻 Reviewer Notes

## 📑 Test Plan

## ✅ Checklist

### General

- [x] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

## ⏭ Next Steps

2022-03-01 21:01 UTC, EisenbergEffect requested changes
A few suggestions.

2022-03-01 21:01 UTC, EisenbergEffect commented on packages/web-components/fast-foundation/docs/integrations/react.md
> +Targeting specific browser versions prevents Babel to transpile down too much to support old JavaScript versions and increasing file size.
```suggestion
Targeting specific browser versions prevents Babel from transpiling too much to support old JavaScript versions, increasing file size.
```

2022-03-01 22:27 UTC, chrisdholt approved these changes

2022-03-02 14:59 UTC, EisenbergEffect approved these changes

2022-03-02 15:17 UTC, merged