feat: horizontal-scroll scroll item into view
microsoft/fast pull request #6091
Opened 2022-06-09 20:55 UTC by robarbms

# Pull Request

## 📖 Description

Adds a method to scroll a given item at an index or a specific item or child of an item into view.

### 🎫 Issues

## 👩‍💻 Reviewer Notes

## 📑 Test Plan

Built tests to check that items are indeed scrolling into view as expected.

## ✅ Checklist

### General

- [x] I have included a change request file using `$ yarn change`
- [x] I have added tests for my changes.
- [x] I have tested my changes.
- [x] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [x] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## ⏭ Next Steps

2022-06-09 21:26 UTC, eljefe223 commented
We should add an example with oversized buttons for demonstrate in the stories file

2022-06-10 19:05 UTC, EisenbergEffect requested changes
For the master branch, all PRs need to have a `type` and a `dependentChangeType` of "prerelease". It's due to a limitation with Beachball while we're shipping mixed alphas/betas. You should be able to choose "prerelease" when running `yarn change` but unfortunately you have to manually edit the change file to fix up the `dependentChangeType`. Sorry about this...

2022-06-10 19:29 UTC, EisenbergEffect approved these changes

2022-06-11 04:39 UTC, scomea approved these changes

2022-06-13 16:09 UTC, eljefe223 approved these changes

2022-06-15 23:51 UTC, merged