Changes how the Slider works in vertical orientation
microsoft/fast pull request #6647
Opened 2023-02-21 20:30 UTC by procload

# Pull Request

## 📖 Description
Closes #5054 by changing the direction of the Slider thumb to instead increase value when sliding upward. This matches the native slider element when in vertical orientation.

### 🎫 Issues
#5054 

## 👩‍💻 Reviewer Notes

The slider should remain the same except for how the value is increased or decreased when it is in a vertical orientation.

## 📑 Test Plan

No tests were affected by this change

## ✅ Checklist

### General

- [x] I have included a change request file using `$ yarn change`
- [x] I have added tests for my changes.
- [x] I have tested my changes.
- [x] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [x] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## ⏭ Next Steps

2023-02-27 19:10 UTC, chrisdholt requested changes
I pulled this down and I noticed that the keyboarding behavior also needs to be updated - FWIW, it seems like this is broken today. Up should increment, but the actual value (and visuals) are going down. Similarly, down should be decrementing but value and visual is going up. Would be great to get a holistic fix in that addresses the keyboarding behavior as well. Let's be sure to add tests if we can to validate that keyboarding increments and decrements as expected.
<img width="117" alt="image" src="https://user-images.githubusercontent.com/13071055/221657566-957be7bb-fc27-4c0c-ba83-b133d5a014eb.png">

2023-03-01 01:27 UTC, procload commented
> I pulled this down and I noticed that the keyboarding behavior also needs to be updated - FWIW, it seems like this is broken today. Up should increment, but the actual value (and visuals) are going down. Similarly, down should be decrementing but value and visual is going up. Would be great to get a holistic fix in that addresses the keyboarding behavior as well. Let's be sure to add tests if we can to validate that keyboarding increments and decrements as expected. <img alt="image" width="117" src="https://user-images.githubusercontent.com/13071055/221657566-957be7bb-fc27-4c0c-ba83-b133d5a014eb.png">

I saw the tests to check `increment()` and `decrement()` in the file, but didn't see anything related to left/right/up/down or any other keyboard commands. It looks like the keypresses are calling these methods. Should I go forward with adding tests for these, and if so, what should I be testing for outside of if the methods fire?

2023-03-01 01:51 UTC, chrisdholt commented
> I saw the tests to check `increment()` and `decrement()` in the file, but didn't see anything related to left/right/up/down or any other keyboard commands. It looks like the keypresses are calling these methods. Should I go forward with adding tests for these, and if so, what should I be testing for outside of if the methods fire?

Check out the tests in Menu here: https://github.com/microsoft/fast/blob/d0ef0d6b1540ed90730187b45bdaf47aa9dcb183/packages/web-components/fast-foundation/src/menu/menu.pw.spec.ts#L327

I'd expect tests to cover the outcomes for behavior for both modes:
- it should increment the value when up arrow is pressed
- it should increment the value when right arrow is pressed
- it should decrement the value when down arrow is pressed
- it should decrement the value when left arrow is pressed

If we had the above currently we'd know that in vertical it's not working, so the goal is to ensure we fix and have that coverage :)

2023-03-03 22:45 UTC, chrisdholt commented on change/@microsoft-fast-foundation-19bde5a4-4383-4eab-9191-79bdf549c6f3.json
> +  "comment": "Changes how the Slider works in vertical orientation by adjusting the slider to increase value when the thumb is moved upwards",
```suggestion
"comment": "Fixes Slider vertical orientation so adjusting the slider increases the value when the thumb is moved upwards and corrects keyboard handling",
```

2023-03-03 22:48 UTC, chrisdholt approved these changes

2023-03-03 23:29 UTC, eljefe223 approved these changes

2023-03-03 23:30 UTC, merged