Add working with decorators doc and updated api-report markdown
microsoft/fast pull request #7012
Opened 2024-08-01 21:41 UTC by janechu

# Pull Request

## 📖 Description

This change adds a document on working without decorators.

### 🎫 Issues

Closes #6376

## ✅ Checklist

### General

- [ ] I have included a change request file using `$ npm run change`
- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [x] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://github.com/microsoft/fast/blob/master/CODE_OF_CONDUCT.md#our-standards) for this project.

2024-08-01 21:47 UTC, davatron5000 approved these changes

2024-08-01 22:44 UTC, radium-v requested changes

2024-08-01 22:44 UTC, radium-v commented on packages/web-components/fast-element/docs/context/api-report.md.api.md
Filename is `api-report.md.api.md`?

2024-08-01 22:44 UTC, radium-v commented on packages/web-components/fast-element/docs/di/api-report.md.api.md
Same filename situation

2024-08-01 22:44 UTC, radium-v commented on sites/website/src/docs/advanced/working-without-decorators.md
> +Most of our documented examples include the use of TypeScript decorators, however as decorators are an unimplemented feature in JavaScript, see [TypeScript documentation](https://www.typescriptlang.o
```suggestion
Most of our documented examples include the use of TypeScript decorators. However, as decorators are an unimplemented feature in JavaScript, using them may not be right for your project. See [TypeScript documentation](https://www.typescriptlang.org/docs/handbook/decorators.html) for details on our implementation.
```

2024-08-01 22:44 UTC, radium-v commented on sites/website/src/docs/advanced/working-without-decorators.md
> +This accepts the same configuration options as the `@attr` so for example to bind a property name that is different from an attribute name:
```suggestion
The static `definition` accepts the same configuration options as the `@attr` decorator. For example, to bind a property name that is different from an attribute name:
```

2024-08-02 16:49 UTC, radium-v approved these changes

2024-08-02 16:56 UTC, merged