Fix binding observer memory leak
microsoft/fast pull request #7023
Opened 2024-09-11 17:58 UTC by m-akinc

# Pull Request

## 📖 Description

Fixes #7022

### 🎫 Issues

#7022

## 👩‍💻 Reviewer Notes

## 📑 Test Plan

No new tests, since branch is about to be frozen anyway.

## ✅ Checklist

### General

- [x] I have included a change request file using `$ npm run change`
- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://github.com/microsoft/fast/blob/master/CODE_OF_CONDUCT.md#our-standards) for this project.

## ⏭ Next Steps

None. Does not apply to mainline.

2024-09-13 01:46 UTC, chrisdholt approved these changes
Would love to get @janechu's review on this as well. Thanks @m-akinc for this fix!

2024-09-13 16:10 UTC, m-akinc commented
> Would love to get @janechu's review on this as well. Thanks @m-akinc for this fix!

She actually approved it a few hours before you. 🙂

2024-09-16 20:02 UTC, m-akinc commented
Is this ready to be merged?

2024-09-25 17:24 UTC, janechu commented
@m-akinc for some strange reason the checks are not running on this PR, so I took your changes and created a PR myself to see what would happen https://github.com/microsoft/fast/pull/7026 and for whatever reason, we are consistently failing some tests on windows.

2024-09-30 18:13 UTC, m-akinc commented
> @m-akinc for some strange reason the checks are not running on this PR, so I took your changes and created a PR myself to see what would happen #7026 and for whatever reason, we are consistently failing some tests on windows.

@janechu Those two slider tests seem suspect. They fail for me locally with slightly different numbers (both with and without my change):
```
Chrome Headless 128.0.0.0 (Windows 10) Slider should constrain and normalize the value when the `step` attribute has been provided and is a float FAILED
        AssertionError: expected 0.4 to equal 0.6
            at dist/esm/__test__/webpack:/dist/esm/slider/slider.spec.js:134:15
            at Generator.next (<anonymous>)
            at fulfilled (dist/esm/__test__/webpack:/node_modules/tslib/tslib.es6.js:71:42)
Chrome Headless 128.0.0.0 (Windows 10) Slider should update the `stepMultiplier` when the `step` attribute has been updated FAILED                                                                                                                         
        AssertionError: expected 4 to equal 6
            at dist/esm/__test__/webpack:/dist/esm/slider/slider.spec.js:142:15
            at Generator.next (<anonymous>)
            at fulfilled (dist/esm/__test__/webpack:/node_modules/tslib/tslib.es6.js:71:42)
```

The tests seem to use pixel values with an assumption that the slider is a certain length in pixels. Maybe that is not reliable. Maybe the default control or browser window width has changed. Given that the fast-element-1 branch is about to be locked down, I'd imagine there's no real drawback to just disabling these two tests if you're convinced they're not failing due to my changes.

2024-10-01 17:26 UTC, janechu commented
Since they are flakey I think it's fine if you skip those tests in this PR so they're working locally, see if that also kicks off the build tests and we can just make a note of it. Thanks for your patience!

2024-10-01 17:32 UTC, m-akinc commented
@janechu pushed change to skip those two tests. Looks like the build tests need approval from a maintainer to run.

2024-10-01 18:47 UTC, janechu commented on packages/web-components/fast-foundation/src/slider/slider.spec.ts
> +describe.only("Slider", () => {
```suggestion
describe("Slider", () => {
```

2024-10-01 18:48 UTC, janechu requested changes
We should remove the only, we're only skipping the 2 tests  I believe.

2024-10-01 19:38 UTC, m-akinc commented on packages/web-components/fast-foundation/src/slider/slider.spec.ts
> +describe.only("Slider", () => {
Thanks! Didn't mean to check that in.

2024-10-02 18:01 UTC, janechu approved these changes

2024-10-02 19:19 UTC, merged

2024-10-15 18:57 UTC, m-akinc commented
@janechu It looks like there are still a few open PRs into the `fast-element-1` branch, but can we get another release from that branch in the meantime?